### ISSUE TITLE
taiga: close taiga window after installing

### ISSUE THREAD

**Issue by soredake** [sorashi/chocolatey-packages#2]
taiga is opens after installing, which i think is undesirable, it's better to close it after install.

**Comment by sorashi** [comment]
For some reason, taiga's setup seems to be configured to open taiga after successful installation *only in silent mode*, which seems backwards. (Currently, this package runs the setup in silent mode, obviously.)

https://github.com/erengy/taiga/blob/b6f440e48b2827dd9b0c680861cf6c498748c306/setup/Taiga.nsi#L237

I will inquire about this, whether it's intentional, and whether it could be fixed upstream. Edit: I asked in discussion https://github.com/erengy/taiga/discussions/1123

In the meantime, I may soon hack up a solution to prevent this in the Chocolatey package itself.

**Comment by soredake** [comment]
I've decided to fix this myself: https://github.com/sorashi/chocolatey-packages/pull/3

**Comment by sorashi** [comment]
Thank you, the package is [under review](https://community.chocolatey.org/packages/taiga/1.4.0.20230519)

**Comment by soredake** [comment]
https://github.com/erengy/taiga/issues/1134
